import type { CheckCommandResult, RevertProofReport } from "../core/types";

export function renderMarkdownReport(report: RevertProofReport): string {
  const lines: string[] = [];

  lines.push("## RevertProof Report");
  lines.push("");
  lines.push(`Status: **${formatStatus(report.status)}**`);
  lines.push(`Risk: **${report.riskLevel}**`);
  lines.push("");
  lines.push("| Check | Result |");
  lines.push("| --- | --- |");
  lines.push(`| Forward checks | ${report.forwardChecksPassed ? "passed" : "failed"} |`);
  lines.push(`| Synthetic revert | ${report.revertSucceeded ? "passed" : "failed"} |`);
  lines.push(`| Revert checks | ${report.revertChecksPassed ? "passed" : "failed"} |`);
  lines.push("");

  if (report.findings.length === 0) {
    lines.push("No findings.");
  } else {
    lines.push("### Findings");
    lines.push("");
    for (const finding of report.findings) {
      lines.push(`- **${finding.severity.toUpperCase()} ${finding.code}**: ${finding.message}`);
      if (finding.paths && finding.paths.length > 0) {
        lines.push(`  Paths: ${finding.paths.map((path) => `\`${path}\``).join(", ")}`);
      }
    }
  }

  if (report.riskCategories.length > 0) {
    lines.push("");
    lines.push("### Risk Categories");
    lines.push("");
    for (const category of report.riskCategories) {
      lines.push(`- **${category.category}**: ${category.paths.map((path) => `\`${path}\``).join(", ")}`);
    }
  }

  lines.push("");
  lines.push("### Changed Paths");
  lines.push("");
  if (report.changedPaths.length === 0) {
    lines.push("No non-ignored changed paths.");
  } else {
    for (const path of report.changedPaths) {
      lines.push(`- \`${path}\``);
    }
  }

  if (report.ignoredPaths.length > 0) {
    lines.push("");
    lines.push("Ignored paths:");
    for (const path of report.ignoredPaths) {
      lines.push(`- \`${path}\``);
    }
  }

  appendCommandSection(lines, "Forward Command Results", report.commandResults.forward);
  appendCommandSection(lines, "Revert Command Results", report.commandResults.revert);

  lines.push("");
  lines.push("<sub>Generated by RevertProof.</sub>");
  return `${lines.join("\n")}\n`;
}

function formatStatus(status: string): string {
  switch (status) {
    case "revert-safe":
      return "revert-safe";
    case "revert-risky":
      return "revert-risky";
    case "not-revert-safe":
      return "not-revert-safe";
    case "not-applicable":
      return "not-applicable";
    default:
      return status;
  }
}

function appendCommandSection(
  lines: string[],
  title: string,
  results: CheckCommandResult[]
): void {
  if (results.length === 0) {
    return;
  }

  lines.push("");
  lines.push(`### ${title}`);
  lines.push("");
  lines.push("| Command | Exit | Duration |");
  lines.push("| --- | ---: | ---: |");

  for (const result of results) {
    lines.push(`| \`${escapePipes(result.command)}\` | ${result.exitCode} | ${result.durationMs}ms |`);
  }
}

function escapePipes(value: string): string {
  return value.replaceAll("|", "\\|");
}
